import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from './ui/dashboard/dashboard.module.css'
import "./ui/globals.css";
import Sidebar from "./ui/dashboard/sidebar/page";
import Navbar from "./ui/dashboard/navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <div className={styles.menu}>
            <Sidebar />
          </div>
          <div className={styles.content}>
            <Navbar />
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
